config/routes.rb
Rails.application.routes.draw do





	root 'home#top'
	get 'home/about'
	get 'search' => 'search#search'

	 devise_for :users
	 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	 resources :users do
	 	resource :relationships, only: [:create, :destroy]
	 	get :follows, on: :member #resource以外のルーティングを設定したい場合にon: :memberを使用する。
	 	get :followers, on: :member #resource以外のルーティングを設定したい場合にon: :memberを使用する。
	 end

	 resources :books do
	 	resources :book_comments, only: [:create, :destroy]
	 	resource :favorites, only: [:create, :destroy]
	 end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy
	validates :title, presence: true
	validates :body, presence: true, length: { maximum: 200 }

    def favorited_by?(user)
      favorites.where(user_id: user.id).exists?
    end

	def Book.search(search, user_or_book, how_search)
        if user_or_book == "2"
            if how_search == "1"
                Book.where(['title LIKE ?', "#{search}"])
            elsif how_search == "2"
                Book.where(['title LIKE ?', "#{search}%"])
            elsif how_search == "3"
                Book.where(['title LIKE ?', "%#{search}"])
            elsif how_search == "4"
                Book.where(['title LIKE ?', "%#{search}%"])
            else
                Book.all
            end
	    end
    end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
	belongs_to :book
	validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :following, class_name: "User"
	belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable



  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id #"Relationship"のactive_relationshipsとは何？Relationshipのforeign_key: :following_idのこと。
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id #"Relationship"のpassive_relationshipsとは何？Relationshipのforeign_key: :follower_idのこと。
  has_many :followers, through: :passive_relationships, source: :following

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  attachment :profile_image
  validates :name, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  def User.search(search, user_or_book, how_search)
      if user_or_book == "1"
        if how_search == "1"
          User.where(['name LIKE ?', "#{search}"])
        elsif how_search == "2"
          User.where(['name LIKE ?', "#{search}%"])
        elsif how_search == "3"
          User.where(['name LIKE ?', "%#{search}"])
        elsif how_search == "4"
          User.where(['name LIKE ?', "%#{search}%"])
        else
          User.all
        end
      end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	def after_sign_in_path_for(resource)
    user_path(current_user.id) # ログイン後に遷移するpathを設定
    end


	before_action :configure_permitted_parameters, if: :devise_controller?
    protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
  	@book = Book.find(params[:book_id])
  	@comment = current_user.book_comments.new(book_comment_params)
  	@comment.book_id = @book.id
  	@comment.save
  end

  def destroy
    @books = Book.find(params[:book_id])
    @comment = BookComment.find_by(id: params[:id], book_id: params[:book_id])
    @comment.destroy
  end


	private
	def book_comment_params
	  params.require(:book_comment).permit(:comment)
	end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  # ログイン前に指定したコントローラを見れなくする
  before_action :correct_user, only: [:edit, :update]

  def index
  	@books = Book.all
    @book = Book.new
  end

  # def new
  # 	@book = Book.new
  # end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id# user_idの情報はフォームからはきていないので、deviseのメソッドを使って「ログインしている自分のid」を代入アソシエーションをした状態でデータの保存をすることができました！
    if @book.save
    redirect_to book_path(@book.id), notice: "Book was successfully created."
    else
    @books = Book.all
    render :index
    end
  end

  def show
    @books = Book.find(params[:id])
    @book = Book.new
    @book_comment = BookComment.new
    # @user = @books.user
  end


  def correct_user
    @book = current_user.books.find_by(id: params[:id])
    unless @book
      redirect_to books_path
    end
  end


  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: "Book was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    if book.destroy
    redirect_to books_path
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
  	@book = Book.find(params[:book_id])
  	favorite = current_user.favorites.new(book_id: @book.id)
  	favorite.save
  end

  def destroy
  	@book = Book.find(params[:book_id])
  	favorite = current_user.favorites.find_by(book_id: @book.id)
  	favorite.destroy
  end
end


#fallbackの後のpathはエラーが起きた場合に戻るページ

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
  	follow = current_user.active_relationships.new(follower_id: params[:user_id])
  	follow.save
  	redirect_back(fallback_location: users_path)
  end

  def destroy
  	follow = current_user.active_relationships.find_by(follower_id: params[:user_id])
    follow.destroy
    redirect_back(fallback_location: users_path)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
	def search
		@user_or_book = params[:option]

		@how_search = params[:choice]

		if @user_or_book == "1"
			@users = User.search(params[:search], @user_or_book, @how_search)
        else
            @books = Book.search(params[:search], @user_or_book, @how_search)
        end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
    # ログイン前に指定したコントローラを見れなくする
    before_action :correct_user, only: [:edit, :update]
  def top
  end

  def show
  	@user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  	# @books = @user.books.page(params[:page]).reverse_order
  end

  def follows
    @user = User.find(params[:id])
    @users = @user.followings
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
  end

  def index
    @book = Book.new
  	@users = User.all
  end

  def correct_user
    @user = User.find(params[:id])
    if
      @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def edit
  	@user = User.find(params[:id])
    #   if
    #   @user != current_user
    #   redirect_to user_path(current_user)、上のcorrect_userと同じ意味
    # end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated book successfully."
    else
      render :edit
    end
  end

  def user_params
  params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_form.html.erb
<%= form_with(model: [books, book_comment] ) do |f| %>
  <div class="form-group">
    <p class="comment-form-p">コメントフォーム</p>
    <%= f.text_area :comment, class: "form-control form-control-lg" %>
    <%= f.submit "送信" %>
  </div>
<% end %>

app/views/book_comments/_index.html.erb
<% books.book_comments.each do |book_comment| %>
<div class="comment-content">
  <%= attachment_image_tag book_comment.user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %>
  <%= book_comment.comment %>
  <% if book_comment.user == current_user %>
    <%= link_to "Dstroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true, class: "btn btn-danger btn-sm" %>
  <% end %>
</div>
<% end %>

app/views/book_comments/create.js.erb
$("#comments_area").html("<%= j(render partial: 'book_comments/index', locals: {books: @book, book_comment: @book_comment}) %>");
$("textarea").val('')

// #comments_areaの後に_<%= @comment.id %>のようなどのidを特定する記述をするのは好ましくない

app/views/book_comments/destroy.js.erb
$("#comments_area").html("<%= j(render partial: 'book_comments/index', locals: {books: @books}) %>");


// #comments_areaの後に_<%= @comment.id %>のようなどのidを特定する記述をするのは好ましくない

app/views/book_comments/index.js.erb
$("#comments_area").html("<%= j(render partial: 'book_comments/index', locals: {books: @books }) %>")

app/views/books/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<h1>Editing Book</h1>
			<div class="row form">
		      <%= form_for(@book) do |f| %>
		      <% if @book.errors.any? %>
		      <h3><%= @book.errors.count %> error</h3>
		      <ul>
			    <% @book.errors.full_messages.each do |message| %>
			    <%= message %>
			  <% end %>
		      </ul>
              <% end %>
		      <div class="row">
		        <h4>title</h4>
		        <%= f.text_field :title, class: "col-xs-12 book_title"%>
		      </div>
		      <div class="row">
		        <h4>opinion</h4>
		        <%= f.text_area :body, class: "col-xs-12 book_opinion" %>
		      </div>
		      <div class="row">
		        	<%= f.submit 'Update Book', class: 'btn btn-primary col-xs-12 book_update edit-update-book' %>
		      </div>
		      <% end %>
		    </div>
		    <div class="row">
		      <%= link_to "Show", book_path(@book.id) %>
	          <span> | </span>
	          <%= link_to "Back", books_path %>
	        </div>
		</div>
		<div class="col-md-3">
		</div>
	</div>
</div>

app/views/books/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<h2>User info</h2>
		    <%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", size:'100x100' %>


		    <table class="table">
				<tbody>
					<tr>
						<th>name</th>
						<th><%= current_user.name %></th>
					</tr>
					<tr>
						<td>introduction</td>
						<td><%= current_user.introduction %></td>
					</tr>
					<tr>
						<td>follows</td>
						<td ><%= link_to current_user.followings.count, follows_user_path(current_user.id) %></td>
					</tr>
					<tr>
						<td>followers</td>
						<td><%= link_to current_user.followers.count, followers_user_path(current_user.id) %></td>
					</tr>
				</tbody>
			</table>



			<div class="row edit">
				<%= link_to edit_user_path(current_user) do %>
				<span class="col-xs-12 btn btn-default glyphicon glyphicon-wrench" aria-hidden="true"></span>
				<% end %>
			</div>


		    <div class="row form">
		      <h2 class="side-newbook">New book</h2>
		      <%= form_for(@book) do |f| %>
		      <% if @book.errors.any? %>
		      <h3><%= @book.errors.count %> error</h3>
		      <ul>
			    <% @book.errors.full_messages.each do |message| %>
			    <%= message %>
			  <% end %>
		      </ul>
              <% end %>
		      <div>
		        <h4>title</h4>
		        <%= f.text_field :title, class: "col-xs-12 book_title"%>
		      </div>
		      <div>
		        <h4>opinion</h4>
		        <%= f.text_area :body, class: "col-xs-12 book_body" %>
		      </div>
		      <div class="">
		        	<%= f.submit 'Create Book', class: "btn btn-primary col-xs-12 side-create" %>
		      </div>
		      <% end %>
		    </div>
	    </div>

		<div class="col-xs-9">
			<h2>Books</h2>
			<table class="table table-hover table-inverse">
				<thead>
					<tr>
						<th></th>
						<th>title</th>
						<th>opinion</th>
						<th colspan="3"></th>
					</tr>
				</thead>
				<% @books.each do |book| %>
				<tbody>
					<tr>
						<td><%= link_to user_path(book.user.id) do %><!-- ログインする前に作った投稿があると各userを認識しなくなる。idを探すからidがない物があるとどれがどれか分からなくなり認識しない -->
							<%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %>
							<% end %>　　　　　　<!-- 画像がある場所 画像がのカラム名-->
						</td>
						<td><%= link_to book.title, book_path(book.id)%></td>
						<td><%= book.body %></td>
						<td id="favorites_buttons_<%= book.id %>">　　<!-- どのボタンかを変数を使って判断してる -->
							<%= render 'favorites/favorite', book: book %>
					    </td>
					    <td>コメント数: <%= book.book_comments.count %></td>
					</tr>
				</tbody>
				<% end %>
			</table>
		</div>
	</div>
</div>

app/views/books/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<h2>User info</h2>
		    <%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", size:'100x100' %>
		    <table class="table">
				<tbody>
					<tr>
						<th>name</th>
						<th><%= current_user.name %></th>
					</tr>
					<tr>
						<td>introduction</td>
						<td><%= current_user.introduction %></td>
					</tr>
					<tr>
						<td>follows</td>
						<td ><%= link_to current_user.followings.count, follows_user_path(current_user.id) %></td>
					</tr>
					<tr>
						<td>followers</td>
						<td><%= link_to current_user.followers.count, followers_user_path(current_user.id) %></td>
					</tr>
				</tbody>
			</table>
			<div class="row edit">
				<%= link_to edit_user_path(current_user) do %>
				<span class="col-xs-12 btn btn-default glyphicon glyphicon-wrench" aria-hidden="true"></span>
				<% end %>
			</div>


		    <div class="row form">
		      <h2 class="side-newbook">New book</h2>
		      <%= form_for(@book) do |f| %>
		      <% if @book.errors.any? %>
		      <h3><%= @book.errors.count %> error</h3>
		      <ul>
			    <% @book.errors.full_messages.each do |message| %>
			    <%= message %>
			  <% end %>
		      </ul>
              <% end %>
		      <div>
		        <h4>title</h4>
		        <%= f.text_field :title, class: "col-xs-12 book_title"%>
		      </div>
		      <div>
		        <h4>opinion</h4>
		        <%= f.text_area :body, class: "col-xs-12 book_body" %>
		      </div>
		      <div class="">
		        	<%= f.submit 'Create Book', class: "btn btn-primary col-xs-12 side-create" %>
		      </div>
		      <% end %>
		    </div>
	    </div>
		<div class="col-xs-9">
			<% if flash[:notice] %>
              <div class="notice">
			    <%= flash[:notice] %>
			  </div>
            <% end %>
			<h2>Book detail</h2>
			<table class="table">
				<tbody>
					<tr>
						<td><%= link_to user_path(@books.user.id) do %>
							<%= attachment_image_tag @books.user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %><br><%= @books.user.name%><% end %></td>
						<td><%= link_to @books.title, book_path(@books.id) %></td>
						<td><%= @books.body %></td>
						<td><% if @books.user == current_user %><%= link_to "Edit", edit_book_path(@books.id) %><% end%></td>
						<td><% if @books.user == current_user %><%= link_to "Destroy", book_path(@books.id), method: :delete %><% end%></td>
						<td id="favorites_buttons_<%= @books.id %>">
							<%= render 'favorites/favorite', book: @books %>
					    </td>
						<td>コメント数: <%= @books.book_comments.count %></td>
					</tr>
				</tbody>
			</table>
			<div class="col-xs-9 book-comment-form">
				<div id="comments_area">
					<%= render 'book_comments/index', {books: @books} %>
				</div>
				<div class="form-group">
					<%= render 'book_comments/form', {books: @books, book_comment: @book_comment} %>
				</div>
            </div>
        </div>
	</div>
</div>

app/views/favorites/_favorite.html.erb
	<% if book.favorited_by?(current_user) %>
	  	<%= link_to book_favorites_path(book.id), method: :delete, remote: true do %>
	  	<i class="glyphicon glyphicon-heart"></i>
	  	<%= book.favorites.count %>
	  	<% end %>
	<% else %>
	  	<%= link_to book_favorites_path(book.id), method: :post, remote: true do %>
		<i class="glyphicon glyphicon-heart-empty"></i>
		<%= book.favorites.count %>
		<% end %>
	<% end %>

app/views/favorites/create.js.erb
$("#favorites_buttons_<%= @book.id %>").html("<%= j(render partial: 'favorites/favorite', locals: {book: @book}) %>");

app/views/favorites/destroy.js.erb
$('#favorites_buttons_<%= @book.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {book: @book}) %>");

app/views/home/about.html.erb
<div class="container">
	<h1>Welcome to
	  <span class="glyphicon glyphicon-book"></span>Bookers!
    </h1>
</div>

app/views/home/top.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-offset-3 col-md-6">
			<main>
			    <h1>welcome to
			    <span class="glyphicon glyphicon-book"></span>
			    <strong>Bookers</strong>  !!
			    </h1>
			    <p>In <span class="glyphicon glyphicon-book"></span>Bookers,</p>
			    <p>you can share and exchange your opinions, inpressions, and emotions</p>
			    <p>about various books!</p>


                <div class="row">
                  <div class="btn btn-info col-xs-10 col-xs-offset-1 sign_in login"><%= link_to "Log in", new_user_session_path %></div>
                </div>
                <div class="row">
			      <div class="btn btn-success col-xs-10 col-xs-offset-1 signup"><%= link_to "Sign Up", new_user_registration_path %></div>
			    </div>
			</main>
		</div>
	</div>
</div>

app/views/relationships/create.html.erb
<h1>Relationships#create</h1>
<p>Find me in app/views/relationships/create.html.erb</p>

app/views/relationships/destroy.html.erb
<h1>Relationships#destroy</h1>
<p>Find me in app/views/relationships/destroy.html.erb</p>

app/views/search/search.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-10">


			<% if @user_or_book == "1"%>
			    <h1>Users</h1>
			    <table class="table">
			    	<thead>
						<tr>
							<th></th>
							<th>name</th>
							<th>introduction</th>
						</tr>
				    </thead>
			        <% @users.each do |user| %>
			        <tbody>
			            <tr>
			            	<td><%= attachment_image_tag user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %></td>
			                <td><%= user.name %></td>
			                <td><%= user.introduction %></td>
			            </tr>
			        </tbody>
			        <% end %>
			    </table>


			<% elsif @user_or_book == "2" %>
			    <h2>books</h2>
			    <table class="table">
			    	<thead>
						<tr>
							<th></th>
							<th>title</th>
							<th>opinion</th>
						</tr>
				    </thead>
			        <% @books.each do |book| %>
			        <tbody>
			            <tr>
			            	<td><%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %></td>
			                <td><%= book.title %></td>
			                <td><%= book.body %></th>
			            </tr>
			        </tbody>
			    <% end %>
			    </table>
			<% else %>
			<% end %>


        </div>
    </div>
</div>

app/views/users/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<h2>User info</h2>
		    <%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>


		    <table class="table">
				<tbody>
					<tr>
						<th>name</th>
						<th><%= current_user.name %></th>
					</tr>
					<tr>
						<td>introduction</td>
						<td><%= current_user.introduction %></td>
					</tr>
					<tr>
						<td>follows</td>
						<td ><%= link_to current_user.followings.count, follows_user_path(current_user.id) %></td>
					</tr>
					<tr>
						<td>followers</td>
						<td><%= link_to current_user.followers.count, followers_user_path(current_user.id) %></td>
					</tr>
				</tbody>
			</table>


			<div class="row edit">
				<%= link_to edit_user_path(current_user) do %>
				<span class="col-xs-12 btn btn-default glyphicon glyphicon-wrench" aria-hidden="true"></span>
				<% end %>
			</div>


		    <div class="row form">
		      <h2 class="side-newbook">New book</h2>
		      <%= form_for(@book) do |f| %>
		      <% if @book.errors.any? %>
		      <h3><%= @book.errors.count %> error</h3>
		      <ul>
			    <% @book.errors.full_messages.each do |message| %>
			    <%= message %>
			  <% end %>
		      </ul>
              <% end %>
		      <div>
		        <h4>title</h4>
		        <%= f.text_field :title, class: "col-xs-12 book_title"%>
		      </div>
		      <div>
		        <h4>opinion</h4>
		        <%= f.text_area :body, class: "col-xs-12 book_body" %>
		      </div>
		      <div class="">
		        	<%= f.submit 'Create Book', class: "btn btn-primary col-xs-12 side-create" %>
		      </div>
		      <% end %>
		    </div>
	    </div>






		<div class="col-xs-9">
			<h2>Users</h2>
			<table class="table table-hover table-inverse">
				<thead>
					<tr>
						<th>image</th>
						<th>name</th>
						<th colspan="3"></th>
					</tr>
				</thead>
				<% @users.each do |users| %>
				<tbody>
					<tr>
						<td><%= attachment_image_tag users, :profile_image, :fill, 59, 50, format: 'jpeg', fallback: "no_image.jpg", size:'40x40'  %></td>
						<td><%= users.name %></td>
						<td><span>フォロー数: </span><%=users.followings.count %></td>
						<td><span>フォロワー数: </span><%=users.followers.count %></td>
						<% if current_user != users %>
							<% if users.followed_by?(current_user) %>
							  <td>
							  	<%= link_to "フォロー外す", user_relationships_path(users.id), method: :delete %>
							  </td>
							<% else %>
							  <td>
							  	<%= link_to "フォローする", user_relationships_path(users.id), method: :post %>
							  </td>
							<% end %>
						<% else %>
						    <td></td>
						<% end %>
						<td><%= link_to "Show", user_path(users.id)%></td>
					</tr>
				</tbody>
				<% end %>
			</table>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<% if flash[:notice] %>
            <div class="notice">
			<%= flash[:notice] %>
			</div>
            <% end %>
			<h2>User info</h2>
		    <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", size:'100x100' %>
		    <table class="table">
				<tbody>
					<tr>
						<th>name</th>
						<th><%= @user.name %></th>
					</tr>
					<tr>
						<td>introduction</td>
						<td><%= @user.introduction %></td>
					</tr>
					<tr>
						<td>follows</td>
						<td ><%= link_to @user.followings.count, follows_user_path(@user) %></td>
					</tr>
					<tr>
						<td>followers</td>
						<td><%= link_to @user.followers.count, followers_user_path(@user) %></td>
					</tr>
				</tbody>
			</table>
			<% if current_user != @user %>
			<div class="follow-btn">
			    <% if @user.followed_by?(current_user) %>
					<%= link_to "フォロー外す", user_relationships_path(@user.id), method: :delete, class: "btn btn-danger btn-sm" %>
				<% else %>
					<%= link_to "フォローする", user_relationships_path(@user.id), method: :post, class: "btn btn-success btn-sm" %>
				<% end %>
			</div>
			<% end %>
			<div class="row edit">
				<% if @user.id == current_user.id %>
					<%= link_to edit_user_path(@user.id) do %>
					<span class="col-xs-12 btn btn-default glyphicon glyphicon-wrench" aria-hidden="true"></span>
					<% end %>
				<% else @user.id != current_user.id %>
					<%= link_to user_path(current_user) do %>
					<span class="col-xs-12 btn btn-default glyphicon glyphicon-wrench" aria-hidden="true"></span>
					<% end %>
				<% end %>
			</div>
		    <div class="row form">
		      <h2 class="side-newbook">New book</h2>
		      <%= form_for(@book) do |f| %>
		      <% if @book.errors.any? %>
		      <h3><%= @book.errors.count %> error</h3>
		      <ul>
			    <% @book.errors.full_messages.each do |message| %>
			    <%= message %>
			  <% end %>
		      </ul>
              <% end %>
		      <div class="">
		        <h4>title</h4>
		        <%= f.text_field :title, class: "col-xs-12 book_title"%>
		      </div>
		      <div class="">
		        <h4>opinion</h4>
		        <%= f.text_area :body, class: "col-xs-12 book_body"%>
		      </div>
		      <div class="">
		        <%= f.submit 'Create Book', class: "btn btn-primary col-xs-12 side-create" %>
		      </div>
		      <% end %>
		    </div>
		</div>


		<div class="col-xs-9">
			<h2>Books</h2>
			<table class="table">
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
						<th colspan="3"></th>
					</tr>
				</thead>
				<% @books.each do |book| %>
				<tbody>
					<tr>
						<td><%= attachment_image_tag @user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %></td>
						<td><%= link_to book.title, book_path(book.id) %></td>
						<td><%= book.body %></td>
						<td>コメント数: <%= book.book_comments.count %></td>
					</tr>
				</tbody>
				<% end %>
			</table>
	    </div>
	</div>
</div>