config/routes.rb
Rails.application.routes.draw do





	root 'home#top'
	get 'home/about'
	get 'search' => 'search#search'

	 devise_for :users
	 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	 resources :users do
	 	resource :relationships, only: [:create, :destroy]
	 	get :follows, on: :member #resource以外のルーティングを設定したい場合にon: :memberを使用する。
	 	get :followers, on: :member #resource以外のルーティングを設定したい場合にon: :memberを使用する。
	 end

	 resources :books do
	 	resources :book_comments, only: [:create, :destroy]
	 	resource :favorites, only: [:create, :destroy]
	 end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy
	validates :title, presence: true
	validates :body, presence: true, length: { maximum: 200 }

    def favorited_by?(user)
      favorites.where(user_id: user.id).exists?
    end

	def Book.search(search, user_or_book, how_search)
        if user_or_book == "2"
            if how_search == "1"
                Book.where(['title LIKE ?', "#{search}"])
            elsif how_search == "2"
                Book.where(['title LIKE ?', "#{search}%"])
            elsif how_search == "3"
                Book.where(['title LIKE ?', "%#{search}"])
            elsif how_search == "4"
                Book.where(['title LIKE ?', "%#{search}%"])
            else
                Book.all
            end
	    end
    end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
	belongs_to :book
	validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :following, class_name: "User"
	belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable



  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id #"Relationship"のactive_relationshipsとは何？Relationshipのforeign_key: :following_idのこと。
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id #"Relationship"のpassive_relationshipsとは何？Relationshipのforeign_key: :follower_idのこと。
  has_many :followers, through: :passive_relationships, source: :following

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  attachment :profile_image
  validates :name, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  def User.search(search, user_or_book, how_search)
      if user_or_book == "1"
        if how_search == "1"
          User.where(['name LIKE ?', "#{search}"])
        elsif how_search == "2"
          User.where(['name LIKE ?', "#{search}%"])
        elsif how_search == "3"
          User.where(['name LIKE ?', "%#{search}"])
        elsif how_search == "4"
          User.where(['name LIKE ?', "%#{search}%"])
        else
          User.all
        end
      end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	def after_sign_in_path_for(resource)
    user_path(current_user.id) # ログイン後に遷移するpathを設定
    end


	before_action :configure_permitted_parameters, if: :devise_controller?
    protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  # ログイン前に指定したコントローラを見れなくする
  before_action :correct_user, only: [:edit, :update]

  def index
  	@books = Book.all
    @book = Book.new
  end

  # def new
  # 	@book = Book.new
  # end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id# user_idの情報はフォームからはきていないので、deviseのメソッドを使って「ログインしている自分のid」を代入アソシエーションをした状態でデータの保存をすることができました！
    if @book.save
    redirect_to book_path(@book.id), notice: "Book was successfully created."
    else
    @books = Book.all
    render :index
    end
  end

  def show
    @books = Book.find(params[:id])
    @book = Book.new
    @book_comment = BookComment.new
    # @user = @books.user
  end


  def correct_user
    @book = current_user.books.find_by(id: params[:id])
    unless @book
      redirect_to books_path
    end
  end


  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: "Book was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    if book.destroy
    redirect_to books_path
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
  	@book = Book.find(params[:book_id])
  	favorite = current_user.favorites.new(book_id: @book.id)
  	favorite.save
  end

  def destroy
  	@book = Book.find(params[:book_id])
  	favorite = current_user.favorites.find_by(book_id: @book.id)
  	favorite.destroy
  end
end


#fallbackの後のpathはエラーが起きた場合に戻るページ

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
	def search
		@user_or_book = params[:option]

		@how_search = params[:choice]

		if @user_or_book == "1"
			@users = User.search(params[:search], @user_or_book, @how_search)
        else
            @books = Book.search(params[:search], @user_or_book, @how_search)
        end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
    # ログイン前に指定したコントローラを見れなくする
    before_action :correct_user, only: [:edit, :update]
  def top
  end

  def show
  	@user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  	# @books = @user.books.page(params[:page]).reverse_order
  end

  def follows
    @user = User.find(params[:id])
    @users = @user.followings
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
  end

  def index
    @book = Book.new
  	@users = User.all
  end

  def correct_user
    @user = User.find(params[:id])
    if
      @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def edit
  	@user = User.find(params[:id])
    #   if
    #   @user != current_user
    #   redirect_to user_path(current_user)、上のcorrect_userと同じ意味
    # end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated book successfully."
    else
      render :edit
    end
  end

  def user_params
  params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>




  <body>
    <header class="navbar navbar-inverse">
      <div class="container">
            <nav class="nav navbar-nav navbar-left">
              <span class="h3">Bookers</span>
            </nav>
            <nav>
                  <ul class="nav navbar-nav navbar-right">
                    <% if user_signed_in? %>
                    <li class="active">
                      <%= link_to user_path(current_user.id) do %>
                        <span class="glyphicon glyphicon-home" aria-hidden="true"></span>  Home
                      <% end %>
                    </li>
                    <li class="active">
                      <%= link_to users_path do %>
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>  Users
                      <% end %>
                    </li>
                    <li class="active">
                      <%= link_to books_path do %>
                        <span class="glyphicon glyphicon-book" aria-hidden="true"></span>  Books
                      <% end %>
                    </li>
                    <li class="active">
                      <%= link_to destroy_user_session_path, method: :delete do %>
                        <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>  logout
                      <% end %>
                    </li>

                    <% else %>

                    <li class="active">
                      <%= link_to root_path do %>
                        <span class="glyphicon glyphicon-home" aria-hidden="true"></span>  Home
                      <% end %>
                    </li>
                    <li class="active">
                      <%= link_to home_about_path do %>
                        <span class="glyphicon glyphicon-link" aria-hidden="true"></span>  About
                      <% end %>
                    </li>
                    <li class="active">
                      <%= link_to new_user_registration_path do %>
                        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>  sign up
                      <% end %>
                    </li>
                    <li class="active">
                      <%= link_to new_user_session_path do %>
                        <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>  login
                      <% end %>
                    </li>
                    <% end %>
                  </ul>
            </nav>
      </div>
    </header>

<% if user_signed_in? %>
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
          <%= form_tag(search_path, :method => 'get') do %>
              <%= select_tag(:option, options_for_select([["user", "1"],["book","2"]]))%>
              <%= select_tag(:choice, options_for_select([["完全一致", "1" ],["前方一致", "2" ],["後方一致", "3" ],["部分一致", "4" ]])) %>
              <%= text_field_tag :search %>
              <%= submit_tag 'Search', :name => nil %>
          <% end %>
      </div>
    </div>
  </div>
<% end %>


      <% if notice %><p><%= notice %></p><% end %>
      <% if alert %><p><%= alert %></p><% end %>
    <%= yield %>
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p class="">CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>